### PR TITLE
Make more static arrays const

### PR DESCRIPTION
**Pull request by ccawley2011**
See also libxmp/libxmp#752.

### CODE REVIEW

**Review by sezero — APPROVED** [review]

**Comment by sezero** [comment]
This is OK by me. @AliceLR ?

And here is a follow-up patch to change driver description into a
driver specific function call: removes the TODO note in sound_oss.
[patch.txt](https://github.com/user-attachments/files/16108972/patch.txt)

**Comment by sezero** [comment]
> And here is a follow-up patch to change driver description into a
> driver specific function call: removes the TODO note in sound_oss.
> [patch.txt](https://github.com/user-attachments/files/16108972/patch.txt)

And if we apply that, maybe we can revert https://github.com/libxmp/xmp-cli/commit/0e44b4ebf62514d35a42a6ec59698f7d614c9115 and adapt? (worth it?)

**Review by AliceLR — APPROVED** [review]

**Comment by sezero** [comment]
Now that this is in, should I create a new PR for the patch [above](https://github.com/libxmp/xmp-cli/pull/65#issuecomment-2210889816)?

**Comment by AliceLR** [comment]
> And here is a follow-up patch
```
+static const char *desc_default = "OSS PCM audio";
+static char descbuf[80] = {0};
```
Given the whole point of this is to reduce the number of mutable globals/statics: this should be computed by the description function and returned via a caller-owned buffer IMO.

> And if we apply that, maybe we can revert [0e44b4e](https://github.com/libxmp/xmp-cli/commit/0e44b4ebf62514d35a42a6ec59698f7d614c9115) and adapt? (worth it?)

Yes, that sounds OK to me.

**Comment by sezero** [comment]
> > And here is a follow-up patch
> 
> ```
> +static const char *desc_default = "OSS PCM audio";
> +static char descbuf[80] = {0};
> ```
> 
> Given the whole point of this is to reduce the number of mutable globals/statics: this should be computed by the description function and returned via a caller-owned buffer IMO.

Do you have a patch (or a draft of it) ?

**Comment by AliceLR** [comment]
> Do you have a patch (or a draft of it) ?

No, I only just saw your patch

**Pull request merged**
